// Generated by CoffeeScript 1.6.3
(function() {
  var Base, Finder, Helpers, compare, moment, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require('./Base');

  Helpers = require('./Helpers');

  moment = require('moment');

  compare = require('operator-compare');

  Finder = (function(_super) {
    __extends(Finder, _super);

    function Finder() {
      _ref = Finder.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Finder.TIME_FORMAT = 'YYYY-MM-DD HH:mm';

    Finder["in"] = function(path) {
      return new Finder(path);
    };

    Finder.from = function(path) {
      return (new Finder(path)).recursively();
    };

    Finder.find = function(path, type) {
      if (type == null) {
        type = 'all';
      }
      path = this.parseDirectory(path);
      return (new Finder(path.directory)).recursively().find(path.mask, type);
    };

    Finder.findFiles = function(path) {
      return Finder.find(path, 'files');
    };

    Finder.findDirectories = function(path) {
      return Finder.find(path, 'directories');
    };

    Finder.prototype.find = function(mask, type) {
      var _ref1;
      if (mask == null) {
        mask = null;
      }
      if (type == null) {
        type = 'all';
      }
      mask = Helpers.normalizePattern(mask);
      if (this.up === true || ((_ref1 = typeof this.up) === 'number' || _ref1 === 'string')) {
        return this.getPathsFromParentsSync(mask, type);
      } else {
        return this.getPathsSync(type, mask);
      }
    };

    Finder.prototype.findFiles = function(mask) {
      if (mask == null) {
        mask = null;
      }
      return this.find(mask, 'files');
    };

    Finder.prototype.findDirectories = function(mask) {
      if (mask == null) {
        mask = null;
      }
      return this.find(mask, 'directories');
    };

    Finder.prototype.size = function(operation, value) {
      this.filter(function(stat) {
        return compare(stat.size, operation, value);
      });
      return this;
    };

    Finder.prototype.date = function(operation, value) {
      this.filter(function(stat) {
        var date;
        switch (Object.prototype.toString.call(value)) {
          case '[object String]':
            date = moment(value, Finder.TIME_FORMAT);
            break;
          case '[object Object]':
            date = moment().subtract(value);
            break;
          default:
            throw new Error('Date format is not valid.');
        }
        return compare((new Date(stat.mtime)).getTime(), operation, date.valueOf());
      });
      return this;
    };

    return Finder;

  })(Base);

  module.exports = Finder;

}).call(this);
