// Generated by CoffeeScript 1.6.3
(function() {
  var Helpers, escape;

  escape = require('escape-regexp');

  Helpers = (function() {
    function Helpers() {}

    Helpers.ASTERISK_PATTERN = '<[0-9a-zA-Z/.-_ ]+>';

    Helpers.parseDirectory = function(path) {
      var asterisk, mask, regexp, splitter;
      mask = null;
      asterisk = path.indexOf('*');
      regexp = path.indexOf('<');
      if (asterisk !== -1 || regexp !== -1) {
        if (asterisk === -1 || (asterisk !== -1 && regexp !== -1 && asterisk > regexp)) {
          splitter = regexp;
        } else if (regexp === -1 || (regexp !== -1 && asterisk !== -1 && asterisk <= regexp)) {
          splitter = asterisk;
        }
        mask = path.substr(splitter);
        path = path.substr(0, splitter);
      }
      return {
        directory: path,
        mask: mask
      };
    };

    Helpers.normalizePattern = function(pattern) {
      var i, part, parts, partsResult, replacement, _i, _len;
      if (pattern === null) {
        return null;
      }
      if (pattern === '*') {
        return null;
      }
      pattern = pattern.replace(/\*/g, Helpers.ASTERISK_PATTERN);
      parts = pattern.match(/<((?!(<|>)).)*>/g);
      if (parts !== null) {
        partsResult = {};
        for (i = _i = 0, _len = parts.length; _i < _len; i = ++_i) {
          part = parts[i];
          partsResult['__<<' + i + '>>__'] = part.replace(/^<(.*)>$/, '$1');
          pattern = pattern.replace(part, '__<<' + i + '>>__');
        }
        pattern = escape(pattern);
        for (replacement in partsResult) {
          part = partsResult[replacement];
          pattern = pattern.replace(replacement, part);
        }
      } else {
        pattern = escape(pattern);
      }
      return pattern;
    };

    return Helpers;

  })();

  module.exports = Helpers;

}).call(this);
