// Generated by CoffeeScript 1.6.3
(function() {
  var Finder, dir, expect, fs, path;

  expect = require('chai').expect;

  path = require('path');

  fs = require('fs');

  Finder = require('../../lib/Finder');

  dir = path.resolve(__dirname + '/../data');

  describe('Finder', function() {
    describe('base', function() {
      return it('should throw an error if path is not directory', function() {
        return expect(function() {
          return new Finder("" + dir + "/two");
        }).to["throw"](Error);
      });
    });
    describe('#findFiles()', function() {
      return it('should return file names from root folder', function() {
        return expect(Finder["in"](dir).findFiles()).to.be.eql(["" + dir + "/0", "" + dir + "/1", "" + dir + "/five", "" + dir + "/one", "" + dir + "/three", "" + dir + "/two"]);
      });
    });
    describe('#findDirectories()', function() {
      return it('should return directory names from root folder', function() {
        return expect(Finder["in"](dir).findDirectories()).to.be.eql(["" + dir + "/eight", "" + dir + "/seven", "" + dir + "/six"]);
      });
    });
    describe('#find()', function() {
      return it('should return file and directory names from root folder', function() {
        return expect(Finder["in"](dir).find()).to.be.eql(["" + dir + "/0", "" + dir + "/1", "" + dir + "/eight", "" + dir + "/five", "" + dir + "/one", "" + dir + "/seven", "" + dir + "/six", "" + dir + "/three", "" + dir + "/two"]);
      });
    });
    describe('#findFirst()', function() {
      it('should return file path', function() {
        return expect(Finder["in"](dir).findFirst().findFiles()).to.be.equal("" + dir + "/0");
      });
      it('should return null', function() {
        return expect(Finder["in"](dir).findFirst().findFiles('randomName')).to.be["null"];
      });
      it('should return file path for first name with two numbers in name', function() {
        return expect(Finder.from(dir).findFirst().findFiles('<[0-9]{2}>')).to.be.equal("" + dir + "/seven/13");
      });
      it('should return null for recursive searching', function() {
        return expect(Finder.from(dir).findFirst().findFiles('randomName')).to.be["null"];
      });
      it('should return first path to directory', function() {
        return expect(Finder.from(dir).findFirst().findDirectories('4')).to.be.equal("" + dir + "/eight/3/4");
      });
      it('should return null when looking into parents', function() {
        return expect(Finder["in"]("" + dir + "/eight/3/4").lookUp(4).findFirst().findFiles('twelve')).to.be["null"];
      });
      return it('should return first file when looking into parents recursively', function() {
        return expect(Finder.from("" + dir + "/eight/3/4").lookUp(4).findFirst().findFiles('twelve')).to.equal("" + dir + "/seven/twelve");
      });
    });
    describe('#recursive()', function() {
      return it('should return file names recursively from find* methods', function() {
        return expect(Finder.from(dir).findFiles()).to.be.eql(["" + dir + "/0", "" + dir + "/1", "" + dir + "/eight/3/4/file.json", "" + dir + "/eight/other.js", "" + dir + "/eight/package.json", "" + dir + "/five", "" + dir + "/one", "" + dir + "/seven/13", "" + dir + "/seven/14", "" + dir + "/seven/twelve", "" + dir + "/six/eleven", "" + dir + "/six/nine", "" + dir + "/six/ten", "" + dir + "/three", "" + dir + "/two"]);
      });
    });
    describe('#exclude()', function() {
      return it('should return files which has not got numbers in name', function() {
        return expect(Finder["in"](dir).exclude(['<[0-9]>']).findFiles()).to.be.eql(["" + dir + "/five", "" + dir + "/one", "" + dir + "/three", "" + dir + "/two"]);
      });
    });
    describe('#showSystemFiles()', function() {
      return it('should return also system, hide and temp files', function() {
        return expect(Finder["in"](dir).showSystemFiles().findFiles()).to.be.eql(["" + dir + "/.cache", "" + dir + "/0", "" + dir + "/1", "" + dir + "/five", "" + dir + "/five~", "" + dir + "/one", "" + dir + "/three", "" + dir + "/two"]);
      });
    });
    describe('#lookUp()', function() {
      it('should return path to file in parent directory', function() {
        return expect(Finder["in"]("" + dir + "/eight/3/4").lookUp(4).showSystemFiles().findFiles('._.js')).to.be.eql(["" + dir + "/eight/._.js"]);
      });
      it('should return first file in parent directorz with depth set by string', function() {
        return expect(Finder["in"]("" + dir + "/eight").lookUp(dir).findFiles('package.json')).to.be.eql(["" + dir + "/eight/package.json"]);
      });
      it('should return null when limit parent is the same like searched directory and file is not there', function() {
        return expect(Finder["in"](dir).lookUp(dir).findFiles('package.json')).to.be.eql([]);
      });
      it('should return path to file in parent directory recursively', function() {
        return expect(Finder.from("" + dir + "/eight/3/4").lookUp(4).findFiles('twelve')).to.be.eql(["" + dir + "/seven/twelve"]);
      });
      return it('should return first file in parent directories with depth set by string', function() {
        return expect(Finder.from("" + dir + "/eight/3/4").lookUp(dir).findFiles('twelve')).to.be.eql(["" + dir + "/seven/twelve"]);
      });
    });
    describe('filters', function() {
      describe('#size()', function() {
        return it('should return files with size between 2000B and 3000B', function() {
          return expect(Finder["in"](dir).size('>=', 2000).size('<=', 3000).findFiles()).to.be.eql(["" + dir + "/five"]);
        });
      });
      describe('#date()', function() {
        return it('should return files which were changed in less than 1 minute ago', function() {
          fs.writeFileSync("" + dir + "/two", 'just some changes');
          return expect(Finder["in"](dir).date('>', {
            minutes: 1
          }).findFiles()).to.be.eql(["" + dir + "/two"]);
        });
      });
      return describe('#filter()', function() {
        return it('should return files which names are 3 chars length', function() {
          var filter;
          filter = function(stat, file) {
            var name;
            name = path.basename(file, path.extname(file));
            return name.length === 3;
          };
          return expect(Finder["in"](dir).filter(filter).findFiles()).to.be.eql(["" + dir + "/one", "" + dir + "/two"]);
        });
      });
    });
    return describe('utils', function() {
      describe('#parseDirectory()', function() {
        return it('should return object with directory and mask from path to find* methods', function() {
          expect(Finder.parseDirectory("" + dir + "/one")).to.be.eql({
            directory: "" + dir + "/one",
            mask: null
          });
          expect(Finder.parseDirectory("" + dir + "<(five|three)*>")).to.be.eql({
            directory: dir,
            mask: '<(five|three)*>'
          });
          return expect(Finder.parseDirectory("" + dir + "*<e$>")).to.be.eql({
            directory: dir,
            mask: '*<e$>'
          });
        });
      });
      describe('#escapeForRegex()', function() {
        return it('should return escaped string for using it in regexp', function() {
          return expect(Finder.escapeForRegex('.h[]e()l+|l?^o$')).to.be.equal('\\.h\\[\\]e\\(\\)l\\+\\|l\\?\\^o\\$');
        });
      });
      return describe('#normalizePattern()', function() {
        return it('should return proper regular expression from path parameter', function() {
          return expect(Finder.normalizePattern("" + dir + "/.temp/<(one|two)>*<$>")).to.be.equal("" + dir + "/\\.temp/(one|two)[0-9a-zA-Z/.-_ ]+$");
        });
      });
    });
  });

}).call(this);
