// Generated by CoffeeScript 1.6.3
(function() {
  var Helpers, expect;

  expect = require('chai').expect;

  Helpers = require('../../lib/Helpers');

  describe('Helpers', function() {
    return describe('#parseDirectory()', function() {
      return it('should return object with directory and mask from path to find* methods', function() {
        expect(Helpers.parseDirectory("/one")).to.be.eql({
          directory: "/one",
          mask: null
        });
        expect(Helpers.parseDirectory("<(five|three)*>")).to.be.eql({
          directory: '',
          mask: '<(five|three)*>'
        });
        return expect(Helpers.parseDirectory("*<e$>")).to.be.eql({
          directory: '',
          mask: '*<e$>'
        });
      });
    });
  });

}).call(this);
